// Generated by gencpp from file turtle_control_pkg/TurtleSpeed.msg
// DO NOT EDIT!


#ifndef TURTLE_CONTROL_PKG_MESSAGE_TURTLESPEED_H
#define TURTLE_CONTROL_PKG_MESSAGE_TURTLESPEED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_control_pkg
{
template <class ContainerAllocator>
struct TurtleSpeed_
{
  typedef TurtleSpeed_<ContainerAllocator> Type;

  TurtleSpeed_()
    : linear_speed(0.0)  {
    }
  TurtleSpeed_(const ContainerAllocator& _alloc)
    : linear_speed(0.0)  {
  (void)_alloc;
    }



   typedef double _linear_speed_type;
  _linear_speed_type linear_speed;





  typedef boost::shared_ptr< ::turtle_control_pkg::TurtleSpeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_control_pkg::TurtleSpeed_<ContainerAllocator> const> ConstPtr;

}; // struct TurtleSpeed_

typedef ::turtle_control_pkg::TurtleSpeed_<std::allocator<void> > TurtleSpeed;

typedef boost::shared_ptr< ::turtle_control_pkg::TurtleSpeed > TurtleSpeedPtr;
typedef boost::shared_ptr< ::turtle_control_pkg::TurtleSpeed const> TurtleSpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_control_pkg::TurtleSpeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_control_pkg::TurtleSpeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtle_control_pkg::TurtleSpeed_<ContainerAllocator1> & lhs, const ::turtle_control_pkg::TurtleSpeed_<ContainerAllocator2> & rhs)
{
  return lhs.linear_speed == rhs.linear_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtle_control_pkg::TurtleSpeed_<ContainerAllocator1> & lhs, const ::turtle_control_pkg::TurtleSpeed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtle_control_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtle_control_pkg::TurtleSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_control_pkg::TurtleSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_control_pkg::TurtleSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_control_pkg::TurtleSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_control_pkg::TurtleSpeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_control_pkg::TurtleSpeed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_control_pkg::TurtleSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4f9da7bc5185841ef96b23f35977b70";
  }

  static const char* value(const ::turtle_control_pkg::TurtleSpeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4f9da7bc5185841ULL;
  static const uint64_t static_value2 = 0xef96b23f35977b70ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_control_pkg::TurtleSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_control_pkg/TurtleSpeed";
  }

  static const char* value(const ::turtle_control_pkg::TurtleSpeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_control_pkg::TurtleSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 linear_speed  # 定义线速度字段\n"
"\n"
;
  }

  static const char* value(const ::turtle_control_pkg::TurtleSpeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_control_pkg::TurtleSpeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurtleSpeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_control_pkg::TurtleSpeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_control_pkg::TurtleSpeed_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "linear_speed: ";
    Printer<double>::stream(s, indent + "  ", v.linear_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_CONTROL_PKG_MESSAGE_TURTLESPEED_H
